### ISSUE TITLE
Twisted hook requirements

### ISSUE THREAD

**Issue by danuker** [chevah/github-hooks-server#33]
For Twisted we need to support "needs-review" and "needs-changes" as non team members don't have access to the PR actions... they can only comment on a PR

and for Twisted and other open source projects in general, you have many PR from non-team members

- [x] Remove [Twisted deps](https://github.com/chevah/github-hooks-server/security/dependabot)
- [ ] For PRs: Ask for review instead of assigning users #44 
- [x] Synonyms for needs-review: **please-review, review-please, please review, review please**
- [x] Reviewers fallback configurable per-repo or per-org #42 
- [x] Make sure it can add `needs-changes` label even on errors setting assignee (when setting assignee to not-yet-contributor)

**Comment by adiroiban** [comment]
For Twisted we need to support only "needs-review" and "needs-changes"

"changes-approved" and "needs-changes" should only be done via the GitHub UI by a "competent" user.

And the important part is to ask the review or (re)review from the fixed `twisted/twisted-contributors` team.

So for Twisted we have:

* #42 
* #44
* #10 - might also be needed for Twisted
